### PR TITLE
Added support for hijacking dynamically  loaded torrent links.

### PR DESCRIPTION
**Pull request by NosBit**

### CODE REVIEW

**Comment by wader** [comment]
I guess this might add duplicate click events on links? probably just wasting some memory but not causing any problems as the click event function stop both default handler and propagation.

**Comment by NosBit** [comment]
It will not add extra click events because you cant have an event attached to the same function twice.

**Comment by wader** [comment]
Ah nice, didn't know that.

**Comment by YodaDaCoda** [comment]
I think I'd be best catching all clicks on all events and testing them within the function, and preventing default and propogation if the HREF matches.

The listener can be added to the BODY tag and filtered to only function on A tags.

I'll need to test, but it'll simplify code somewhat.

Could you provide a URL that I can test dynamic torrent link catching on?

**Comment by NosBit** [comment]
I made a test page for you http://run.plnkr.co/sPllUpkpxUlQ85EZ/

**Comment by YodaDaCoda** [comment]
I'd appreciate if you guys could test this with the latest commit. Please note that all links will be captured by the extension regardless of whether or not you have options configured to download locally. This will be fixed before release to market.

**Comment by NosBit** [comment]
Tested works fine.

**Pull request closed without merging**
