### PR TITLE
Change to ALT double click to also delete data

### PR DESCRIPTION
**Pull request by wader**
CTRL double click seems to not work anymore and instead now
brings up the context menu.

### CODE REVIEW

**Comment by wader** [comment]
We could keep using CTRL but then i think we need to intercept the "contextmenu" event and use a timer to emulate double click hmm. Is there some other way?

**Comment by YodaDaCoda** [comment]
CTRL works fine for me. What version of Chrome and OS are you using?

**Comment by wader** [comment]
Aha, i use Chrome 43.0.2357.81 on OS X

**Comment by wader** [comment]
So maybe never worked on OS X then? delete on both CTRL and ALT?

**Comment by YodaDaCoda** [comment]
I'll test on Windows and Linux tomorrow. If alt works fine on those I'll switch to just alt. Otherwise ctrl/alt.

**Comment by wader** [comment]
Ok nice!

**Pull request merged**
